# Kafka configuration
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
    properties:
      schema-registry-url: http://localhost:8081

# Kafka variables
kafka:
  topic:
    create-captain-transaction:
      name: topic_waleed